version: '3.9'

services:
  app:
    build: .
    env_file: .env.${RAILS_ENV}
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "3050:3050"

  db:
    image: postgres:15
    env_file: .env.${RAILS_ENV}
