[build]
buildCommand = "bundle install"

[deploy]
startCommand = "bundle exec puma -C config/puma.rb"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "never"

[env]
RAILS_SERVE_STATIC_FILES = "true"
RAILS_LOG_TO_STDOUT = "true"
